question =    "Xe buýt nào đến thành phố Huế lúc 22:00HR ?"
#question =    "Xe bus nào đến thành phố Hồ Chí Minh ?"
#question =    "Những xe bus nào đi đến Huế ?"
#question =    "Những xe nào xuất phát từ thành phố Hồ Chí Minh ?"
#question =    "Những xe nào đi từ Đà nẵng đến thành phố Hồ Chí Minh ?"
#question =    "Thời gian xe buýt B3 từ Đà Nẵng đến Huế ?"

#question = "   Xe bus nào đi đến thành phố Huế lúc 20:00HR ?   "
#question = "Thời gian nào xe bus B3 đi từ Đà Nẵng đến thành phố Hồ Chí Minh ?"
#question = "Thời gian nào xe bus B3 đi từ Đà Nẵng ?"
#question = "Thời gian nào xe bus B3 đi đến thành phố Hồ Chí Minh ?"
#question = "Xe bus nào đi đến thành phố Hồ Chí Minh ?"
#question = "Những xe bus nào đi đến Huế ?"
#question = "Những xe nào xuất phát từ thành phố Hồ Chí Minh ?"
#question = "Những xe nào đi từ Đà nẵng đến thành phố Hồ Chí Minh ?"